INSERT INTO product (name, price, insert_date) VALUES('Name 1', 100, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 2', 150, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 3', 200, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 4', 400, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 5', 210, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 6', 130, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 7', 120, NOW());
INSERT INTO product (name, price, insert_date) VALUES('Name 8', 110, NOW());